<a href="https://colab.research.google.com/github/hyehyuni/essa/blob/main/ESAA_hw0310.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[개념 정리]**
**3/13 과제 - 파이썬 머신러닝 완벽가이드 pg.1~38 부분**

---


# **Numpy**
파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 루프를 사용하지 않고 대량의 데이터 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보인다. 


---


# 넘파이 ndarray 개요
* np.array() : 변환을 원하는객체를 인자로 입력하면 ndarray를 반환한다.
* ndarray.shape : ndarray의 차원과 크기를 튜플 형태로 나타냄 
* ndarray.ndim : ndarray의 차원을 확인

In [4]:
# 넘파이 모듈 임포트하기 
import numpy as np

# np.array 사용하기 
array1=np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

# array 차원 확인하기 
print('array1: {:0}차원, array2: {:1}차원,  array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원,  array3:  2차원


# ndarray의 데이터 타입 
ndarray 내의 데이터값은 숫자값, 문자열 값, 불 값 등이 모두 가능하다.
* ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다. (한개의 객체에 하나의 타입만)
* ndarray내의 데이터 타입은 dtype 속성으로 확인 가능
* 만약, 서로 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면, 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용
* astype : ndarray 내 데이터 값의 타입 변경 

In [12]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

list2=[1,2,'test']
array2=np.array(list2) # int가 유니코드로 변형
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3) # int가 float으로 변형 
print(array3, array3.dtype)

# astype 메소드 사용하기
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)
array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)
array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64
[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray를 편리하게 생성하기 
1.   arange()
2. zeros()
3. ones()


In [15]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


* reshape() : ndarray의 차원과 크기를 변경


>  -1을 인자로 사용하면 shape를 자동으로 새롭게 생성해 변환한다.


> reshape(-1,1)과 같은 형태로 자주 사용되는데, 이는 원본 ndarray가 어떤 형태라도 2차원이고, 여러개의 로우를 가지되 반드시 한개의 칼럼을 가진 ndarray로 변환됨을 보장한다. 





In [24]:
array1=np.arange(10)
print('array1:\n', array1)
array2=array1.reshape(2,5)
print('array2:\n', array2)
array3=array1.reshape(5,2)
print('array3:\n', array3)

# 지정된 사이즈로 변경이 불가능하면 오류 발생
# array1.reshape(4,3)

array1=np.arange(10)
print(array1)
array2=array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3.shape:', array3.shape)

# 변경할 수 없는 크기인 경우 에러 발생 
# array1=np.arnage(10)
# array4=array1.reshape(-1,4)

# tolist(): 리스트 자료형으로 변환 
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist()) 

# 3차원 ndarray를 2차원 ndarray로 변환 
array5=array3d.reshape(-1,1)
print('array3:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환 
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3.shape: (5, 2)
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


# 넘파이 인덱싱 

1.   특정 데이터만 추출 
* 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환된다.

2.   슬라이싱 
* 슬라이싱은 연속된 인덱스 상의 ndarray를 추출하는 방식, ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1 위치에 있는 데이터를 반환 

3. 팬시 인덱싱 
* 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환 
4. 불린인덱싱 
* 특정 조건에 해당하는지 여부인 T/F 값 인덱싱 집합을 기반으로 T에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환 




1) 단일 값 추출 
*  axis 0은 로우 방향의 축을 의미하며, axis1은 칼럼 방향의 축을 의미한다. 축 기반의 연산에서 axis가 생략되어 있다면 axis0을 의미한다.

In [31]:
array1=np.arange(start=1, stop=10)
print('array1:', array1)
value=array1[2]
print('value:', value)
print(type(value))
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

# 데이터 값 수정하기 
array1[0]=9
array1[8]=0
print('array1:', array1)

# 다차원에서 값 추출하기 
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0])
print('(row=0,col=1) index 가리키는 값:', array2d[0,1])
print('(row=1,col=0) index 가리키는 값:', array2d[1,0])
print('(row=2,col=2) index 가리키는 값:', array2d[2,2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


2) 슬라이싱 
* 슬라이싱 기호 ':', 시작 종료 인덱스는 생략이 가능하다

In [33]:
array1=np.arange(start=1, stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [37]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)
array5=array1[3:]
print(array5)
array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [39]:
# 2차원에서 슬라이싱 
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array3d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

print(array2d[0])
print(array2d[1])
print('array2d[0 shape:', array2d[0].shape, 'array2d[1 shape:', array2d[1].shape)


array3d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]
[1 2 3]
[4 5 6]
array2d[0 shape: (3,) array2d[1 shape: (3,)


3) 팬시 인덱싱 

In [40]:
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2[[0,1],2]=>', array3.tolist())

array4=array2d[[0,1], 0:2]
print('array2d[[0,1],0:2]=>', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]]=>', array5.tolist())

array2[[0,1],2]=> [3, 6]
array2d[[0,1],0:2]=> [[1, 2], [4, 5]]
array2d[[0,1]]=> [[1, 2, 3], [4, 5, 6]]


4) 불린 인덱싱 
* step1 : array1d>5와 같이 ndarray의 필터링 조건을 []안에 기재 
* step2: False 값은 무시하고 True 값에 해당하는 인덱스 값만 저장
* step3: 저장된 인덱스 데이터 세트로 ndarray 조회

In [47]:
array1d=np.arange(start=1, stop=10)
array3=array1d[array1d>5]
print('array1d>5  불린 인덱싱 결과 값:', array3)

array1>5 # True, False를 반환

boolen_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolen_indexes]
print('불린 인덱스로 필터링한 결과: ', array3)

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

array1d>5  불린 인덱싱 결과 값: [6 7 8 9]
불린 인덱스로 필터링한 결과:  [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]


# 행렬의 정렬 
sort()와 argsort() 알아보기 

1. sort()
* np.sort()와 같이 넘파이에서 sort를 호출하는 방식 
* ndarray.sort()와 같이 행렬 자체에서 sort를 호출하는 방식 
* 내림차순으로 정렬하기 위해서는 [::-1] 사용 


In [54]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)

sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array) # 원본행렬은 변하지 않음 

sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array) # 원본행렬이 변함 

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [55]:
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


* 행렬이 2차원 이상인 경우 정렬하는 방법 

In [57]:
array2d=np.array([[8,12],
                  [7,1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


2. argsort()
* 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환한다. 

In [59]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices) 

org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc) 

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [60]:
name_array=np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array=np.array([78,95,84,98,88])
sort_indeices_asc=np.argsort(score_array)
print('성적 오름차순 정렬시 score_array의 인덱스: ', sort_indeices_asc)
print('성적 오름차순 정렬시 name_array의 이름 출력: ', name_array[sort_indeices_asc])

성적 오름차순 정렬시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차순 정렬시 name_array의 이름 출력:  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산 
행렬 내적과 전치행렬 구하기 

1. 행렬 내적 (행렬 곱) 구하기 : np.dot()

In [61]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


2. 전치 행렬구하기 : transpose()

In [63]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
