<a href="https://colab.research.google.com/github/hyehyuni/essa/blob/main/%EC%A0%95%EA%B7%9C%EC%84%B8%EC%85%98_Numpy_0313.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.version)
np.show_config()

<module 'numpy.version' from '/usr/local/lib/python3.9/dist-packages/numpy/version.py'>
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    lib

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
# nbyte를 사용
print(a.nbytes)

80

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
b=np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
c=np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
d=np.arange(9)
d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
# np.where 사용하는 방법
e=np.array([1,2,0,0,4,0])
np.where(e!=0) # 인덱스를 반환함 

# np.nonzero 사용하는 방법 
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


array([1, 2, 4])

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
array1=np.eye(3)
print(array1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
array2=np.random.randn(3,3,3)
print(array2)

[[[ 0.32098216  0.85576388 -0.58726213]
  [-1.49875351 -0.19170677  1.23792866]
  [-1.04392565  0.29696353  0.36635826]]

 [[ 0.15431461 -0.18769887  2.55660054]
  [ 0.01941208  0.71464224 -1.51109205]
  [ 0.05633264  0.72796596  0.02716727]]

 [[-1.71249857  0.46574561 -0.33144761]
  [ 0.60859276  1.53097534 -1.09957181]
  [-0.30347065 -0.62133471 -0.64013243]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
array3=np.random.randn(10,10)
print(array3)
print('최솟값:', array3.min())
print('최댓값:',array3.max())

[[ 0.27963566 -0.64689222 -0.29292995 -0.82211785 -0.37578737  2.61454065
   0.99604654  0.35993483  0.13693727 -0.01822434]
 [ 0.29506639 -0.29811472  0.32609433 -0.62571405  0.61894284 -2.51846277
   1.14982471 -1.10820414  0.59429613  1.62001217]
 [-1.15265703  2.10139845 -0.37783538 -0.5640365   2.35707121  0.1366033
   0.52749677  0.79445493 -0.20329539  0.92949569]
 [ 0.75436245 -0.47852986 -0.78896837  0.11675639 -0.94910866  0.41408086
  -1.33197071  0.3202324  -0.06565493  0.02221464]
 [ 1.72702113 -1.85899588  0.51039731 -0.69177465  0.42277367  0.43086652
  -1.80954755 -0.29300963 -1.31497754  0.22752027]
 [-0.16787822  1.33910684  0.01738701 -1.08259376  0.04273055  1.16286822
   0.03978878  1.16148002 -0.43443613  0.69799922]
 [-1.25294117  0.64898042 -0.11204906  0.59249     0.03010052 -1.76990768
  -0.09991682  1.51586534  1.06946283  1.1472201 ]
 [-1.97252217  0.55664836 -0.21365239  0.19891405 -1.06178401  0.17569027
   0.5470862  -0.25548194 -0.26895408  0.44985505]
 

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
array4=np.random.randn(30)
print(array4)
print('평균:', array4.mean())

[-0.41357091  0.84578771  0.20315318 -0.20395189  0.65167     1.11753178
 -0.04733911  0.25488716  0.25847432  0.46573408  0.59571451  0.94266142
  0.63749811 -1.19192541  0.81698138 -0.55537086 -1.6866911  -0.43212153
  1.17477503 -0.11957364  1.20514673  1.57523026 -0.27130411  0.56480124
 -0.7888967  -0.11181823 -0.5318348   1.47746637  2.00821339  1.12210359]
평균: 0.3187810664959256


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array5=np.ones((4,4))
print(array5)

array5[1:3, 1:3]=0
print(array5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan
# False
# False
# nan
# np.nan in set([np.nan]) : True 
# 0.3 == 3 * 0.1 : False 

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
# k를 사용하여 위치를 조정할 수 있음 
array6=np.diag([1,2,3,4], k=-1)
print(array6)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
array7=np.zeros((8,8))
print(array7)

array7[1::2, 0::2]=1
array7[0::2, 1::2]=1
print(array7)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [109]:
array8=np.random.random((6,7,8))
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
z=np.random.random((5,5))
z=(z-np.mean(z))/(np.std(z))
print(z)

[[-0.17946476  1.712921   -0.51809324 -0.77290582 -1.15381844]
 [ 0.44772912 -0.99193488 -1.10122769  0.37346724  1.17157064]
 [-0.07925299  1.01071613  0.4930044   1.52082556 -0.60218847]
 [ 1.58413588 -0.86469661 -1.65511921 -1.63179712  0.05632215]
 [-0.0455971   0.80830193 -1.10646639  1.13470925  0.38885942]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color=np.dtype([("R", np.ubyte,1),
                ("G", np.ubyte,1),
                ("B", np.ubyte,1),
                ("A", np.ubyte,1)])

<ipython-input-83-0bca8b2ad896>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("R", np.ubyte,1),


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
mat1=np.dot(np.ones((5,3)),np.ones((3,2)))
print(mat1)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z=np.arange(11)
Z[(3<Z)&(Z<8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [108]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [ ]:
# 9 
# 10 

9
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(10)
# Z<Z>Z만 오류가 발생한다. 

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan
# 0
# array([-9.22337204e+18])

nan
0


<ipython-input-94-49e15e2ee0e9>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-94-49e15e2ee0e9>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3